# Generated by Django 3.0.3 on 2020-08-19 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('book_cover', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('uploader', models.TextField()),
                ('publication', models.TextField()),
                ('year', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.Author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.Genre')),
            ],
        ),
    ]
