# Generated by Django 3.0.3 on 2020-08-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_auto_20200819_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
